PLAYER_HEALTH: int = 5  # HP
PLAYER_INVULNERABLE_COOLDOWN_DURATION: float = 1.0  # seconds
PLAYER_SPEED: float = 160.0  # px/s
PLAYER_ANGULAR_SPEED: float = 180.0  # deg/s
PLAYER_SHOOTING_COOLDOWN: float = 0.1  # seconds
PLAYER_BULLET_SPEED: float = 800.0  # px/s

ENEMY_SPAWNER_HEALTH: int = 45  # HP
ENEMY_SEPARATION_ACTIVATE_RADIUS: float = 32.0  # px
ENEMY_SEPARATION_FORCE_WEIGHT: float = 10.0

ENEMY_SPEED = 80  # px/s
