PLAYER_HEALTH = 10
PLAYER_SPEED = 160  # px/s
PLAYER_BULLET_DAMAGE = 3  # HP/hit
PLAYER_ANGULAR_SPEED = 180  # deg/s
PLAYER_BULLET_SPEED = 800  # px/s

ENEMY_SPAWNER_HEALTH = 100
ENEMY_HEALTH = 5
ENEMY_SEPARATION_ACTIVATE_RADIUS: float = 32.0
ENEMY_SEPARATION_FORCE_WEIGHT: float = 10.0

ENEMY_SPEED = 80  # px/s
